### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by idserda** [sticilface/ESP8266-wifi#3]
This looks like a great project! I have some trouble compiling it however. The 4 libraries are installed.  Arduino IDE 1.6.5, esp8266 board 1.6.5-947-g39819f0. Any idea? Thanks!

```
c_ws2812.ino: In function 'void handle_WS2812()':
c_ws2812:188: error: 'FPSTR' was not declared in this scope
c_ws2812.ino: In function 'void handle_lights_config()':
c_ws2812:811: error: 'FPSTR' was not declared in this scope
mqqt_config.ino: In function 'void handle_mqtt()':
mqqt_config:177: error: 'FPSTR' was not declared in this scope
web_server.ino: In function 'void handle_wifi()':
web_server:161: error: 'FPSTR' was not declared in this scope
web_server.ino: In function 'void handle_misc()':
```

**Comment by sticilface** [comment]
I think this suggests that you are using an older version of the arduino IDE.  How recently have you upgraded using the boards manager?  i found this

## 1.6.5-947-g39819f0

36  July 23, 2015

which means that things will have moved on a lot since then.  The esp8266 arduino IDE is quite fast moving at the moment.  I suggest going to github repository and following the instructions to install the latest stable version. 

hope that helps?

**Comment by idserda** [comment]
Just switched to the staging version of the esp8266 library (1.6.5-1160-gef26c5f, from 30-09-2015). Everything compiles fine now, thanks!
